### ISSUE TITLE
False Error on WP 4.3

### ISSUE THREAD

**Issue by FrancescoCarlucci** [boogah/Force-Strong-Passwords#21]
After WP 4.3 upgrade, I get an error when I add a user with Author/Editor/Admin or custom role, even if the password is strong!

I contacted my hosting support (WP Engine) who confirmed is a plugin bug affecting non-English WP install.

If you want I can setup a staging environment for you to test.

**Comment by boogah** [comment]
Hey @FrancescoCarlucci 

Thanks for the bug! I work for WP Engine, so no need for the staging environment. :smiley: 

I've got a fix in that should take care of what you're seeing. It'll take WP Engine a few days to roll it out, but you can have their support grab a copy of this repo to get you patched up until then.

**Comment by FrancescoCarlucci** [comment]
Awesome ;) thank you so much!!
