### ISSUE TITLE
Not working on 4.3, class issue.

### ISSUE THREAD

**Issue by jjeaton** [boogah/Force-Strong-Passwords#22]
This line:

https://github.com/boogah/Force-Strong-Passwords/blob/master/force-zxcvbn.js#L14

should be

`( this ).append( '<input type="hidden" name="slt-fsp-pass-strength-result" value="' + psr.text() + '">' );`

What's getting sent is the classnames which are "hide-if-no-js strong" which means it is always failing even if strong.

I noticed the version running on WPEngine already has this fix.

**Comment by boogah** [comment]
Thanks for the report!

I went about fixing this in a different way. The new version has already been deployed at WP Engine (I work there) and appears to be working for all the customers there.

Give it a try for yourself and let me know if you have any further issues.
