### ISSUE TITLE
how to disable this in WPEngine

### ISSUE THREAD

**Issue by cheapstairparts** [boogah/Force-Strong-Passwords#29]
WPEngine has this plugin as Must Use and it's causing issues. 

So right now when a customer checks out via woocommerce  they are able to create even the weakest password during the checkout page, and it's fine. 

However when a customer goes to the woocommerce  **/my-account/**  page   it won't allow a customer to create the account unless they can come up with this magic strong password. 

Naturally this is causing an increase in abandoned orders as customers get frustrated and leave. 

How could I disable this feature on the Woocommerce My Account page?

**Comment by boogah** [comment]
WP Engine doesn't allow customers to uninstall this plugin, unfortunately.

Here's a plugin that'll disable FSP for you though:

https://github.com/boogah/nofsp

Hope this helps!
