### ISSUE TITLE
WooCommerce support?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [boogah/force-strong-passwords#32]
I saw on old issue where someone was having issues with WooCommerce passwords:

https://github.com/boogah/force-strong-passwords/issues/29

Was this issue resolved? Does this plugin fully support WooCommerce?

**Comment by boogah** [comment]
The issue in #29 wasn't with WooCommerce as much as it was with customers of that particular user getting frustrated with `zxcvbn` requirements.

As long as you are comfortable with customers *having to* set a strong password, you should be fine using this on a WooCommerce site.
